version: 2
jobs:
  build:
    working_directory: ~/my-multi-module-mvn-prj

    docker:
      - image: circleci/openjdk:8-jdk-stretch

    steps:
      - checkout

      - run:
          name: Generate cumulative pom.xml checksum
          command: |
            find . -type f -name "pom.xml" -exec sh -c "sha256sum {} >> ~/pom-checksum.tmp" \;
            sort -o ~/pom-checksum ~/pom-checksum.tmp
          when: always

      - restore_cache:
          keys:
            - my-multi-module-mvn-prj-{{ checksum "~/pom-checksum" }}
            - my-multi-module-mvn-prj-

      - run: mvn de.qaware.maven:go-offline-maven-plugin:resolve-dependencies

      - save_cache:
          paths:
            - ~/.m2
          key: my-multi-module-mvn-prj-{{ checksum "~/pom-checksum" }}

      - run: mvn package

      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always      # Then run your tests!
      - run:
          name: Test
          command: mvn integration-test

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  sample: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - build-and-test
