version: 2
jobs:
  build:
    docker:
      # specify the veresion you desire here
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo

    environment:
      MAVEN_OPS: -Xmx3200m

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependecies-{{ checksum "pom.xml" }}
            - v1-dependecies-

      - run: mvn dependecy:go-offline
      - save_cache:
          key: v1-dependecies-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2

      - run: mvn integration-test


#workflows:
#  maven_test:
#    jobs:
#      - maven/test # checkout, build, test, and upload test results
